### ISSUE TITLE
segmentation result problem

### ISSUE THREAD

**Issue by morte2025** [cavayangtao/lidar_clustering_bench#1]
您好，我的论文有打算用你们的benchmark来评估聚类效果, 但是有一些问题， 请问各个算法的聚类结果是不是要输出为一个txt文档， 但是我看聚类算法里的代码并没有输出为txt的程序，此外，提供的rosbag包输出的点云话题是/velodyne_packets，并不是velodyne_points的消息类型

**Comment by cavayangtao** [comment]
> 您好，我的论文有打算用你们的benchmark来评估聚类效果, 但是有一些问题， 请问各个算法的聚类结果是不是要输出为一个txt文档， 但是我看聚类算法里的代码并没有输出为txt的程序，此外，提供的rosbag包输出的点云话题是/velodyne_packets，并不是velodyne_points的消息类型

您好，聚类可以直接保存terminal里的结果，比如：roslaunch xxx 2>output.txt。
输出/velodyne_points取消launch文件夹中bag_play.launch相应的注释即可。

**Comment by morte2025** [comment]
感谢你的回复，我复现了你的结果，不过还有些小问题，
对于L-CAS datase数据集，我用欧式聚类，不去除地面IoU是 0.3470，
去除后是0.3323， 为啥IoU反而降低了，请问这个正常吗，是不是这个数据集标注时没有去除地面呢，
此外bag_play.launch我看你设置-r 0.05, 这个是否必要呢？
谢谢啦

**Comment by cavayangtao** [comment]
> 感谢你的回复，我复现了你的结果，不过还有些小问题， 对于L-CAS datase数据集，我用欧式聚类，不去除地面IoU是 0.3470， 去除后是0.3323， 为啥IoU反而降低了，请问这个正常吗，是不是这个数据集标注时没有去除地面呢， 此外bag_play.launch我看你设置-r 0.05, 这个是否必要呢？ 谢谢啦

行人的聚类框比较小，去除地面有可能会多切，导致IoU略微下降，L-CAS地面比较平，可以尝试调整聚类算法中的参数直接切除地面。
每个包播放很慢是因为autoware和euclidean跑的比较慢，可能会导致丢帧，这里IoU主要还是考察聚类精度，runtime单独给出了结果。
